KafkaServer {
    com.sun.security.auth.module.Krb5LoginModule required
    useKeyTab=true
    storeKey=true
    keyTab="/etc/kafka/secrets/kafka.server.keytab"
    principal="kafka/localhost@KAFKA.LOCAL";
};
