spring:
  application:
    name: springboot-samples-gateway
  profiles:
    active: dev,local
    include:
      - tracing
  reactor:
    context-propagation: auto
  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 30000
            response-timeout: 120s
            pool:
              max-idle-time: 10s
          globalcors:
            corsConfigurations:
              '[/**]':
                allowed-origin-patterns: "*"
                allowed-methods: "*"
                allowed-headers: "*"
                allow-credentials: true
          routes:
            - id: springboot-samples-admin-client
              uri: http://localhost:8091
              predicates:
                - Path=/springboot-samples-admin-client/**,
              filters:
                - RewritePath=/(?<prefix>springboot-samples-admin-client)/(?<segment>.*), /$\{segment}
            - id: springboot-samples-config-client
              uri: http://localhost:8093
              predicates:
                - Path=/springboot-samples-config-client/**,
              filters:
                - RewritePath=/(?<prefix>springboot-samples-config-client)/(?<segment>.*), /$\{segment}
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_FIRST


server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty.http.client: DEBUG
    reactor.netty.http.server: DEBUG

springdoc:
  swagger-ui:
    enabled: true
    displayOperationId: true
    urls:
      - name: springboot-samples-admin-client
        url: /springboot-samples-admin-client/v3/api-docs
      - name: springboot-samples-config-client
        url: /springboot-samples-config-client/v3/api-docs
  api-docs:
    enabled: true

---
spring.config.activate.on-profile: local

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: prod