input {
  # 接收来自 Filebeat 的数据
  beats {
    port => 5044
  }
}

filter {
  # 1. 核心解析 (针对你的日志格式定制)
  grok {
    match => { 
      # 解释：
      # (?:\[%{DATA:trace_id},%{DATA:span_id}\]\s+)? 
      # 这段正则的意思是：尝试去匹配 [traceId,spanId] 这种格式。
      # 问号 ? 代表“如果没有也不报错”（比如系统刚启动还没Trace的时候）。
      "message" => "%{TIMESTAMP_ISO8601:log_time}\s+%{LOGLEVEL:log_level}\s+(?:\[%{DATA:trace_id},%{DATA:span_id}\]\s+)?%{NUMBER:pid}\s+---\s+\[%{DATA:thread_name}\]\s+%{JAVACLASS:class_name}\s+:\s+%{GREEDYDATA:log_content}" 
    }	
  }

  # 2. 时间修正：用日志里的时间覆盖采集时间
  date {
    match => ["log_time", "yyyy-MM-dd HH:mm:ss.SSS"]
    target => "@timestamp"
    timezone => "Asia/Shanghai" 
  }

  # 3. 清理逻辑
  # 如果 trace_id 没抓到（比如为空），就把这两个字段移除，免得在 Kibana 显示横杠
  if ![trace_id] {
    mutate {
      remove_field => ["trace_id", "span_id"]
    }
  }

  # 4. 删除多余的垃圾字段，给 ES 节省空间
  mutate {
    remove_field => ["log_time", "beat", "input", "prospector", "offset", "host", "agent", "ecs"]
  }
}

output {
  # 发送到 Elasticsearch
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    # 索引名按天自动生成
    index => "springboot-logs-%{+YYYY.MM.dd}"
  }
  
  # 调试专用：会在 Logstash 后台打印，方便你出错时查看
  stdout {
    codec => rubydebug
  }
}