spring:
  application:
    name: springboot-samples-admin-client
  boot:
    admin:
      client:
        url: http://localhost:8090

server:
  port: 8091

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always