spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckInterval: 15s
        instance-id: ${spring.application.name}:${spring.cloud.client.hostname}
  application:
    name: springboot-samples-consul
server:
  port: 8082