spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckInterval: 15s
        instance-id: ${spring.application.name}:${spring.cloud.client.hostname}
  application:
    name: springboot-samples
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: false
    pool:
      enabled: false
server:
  port: 8080